# Generated by Django 5.0.4 on 2024-05-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='titulo',
            field=models.CharField(choices=[('LX01', 'Luxo_Feminino'), ('LX02', 'Luxo_MAsculino'), ('PM01', 'Premium_Feminino'), ('PM02', 'Premium_Masculino')], max_length=40),
        ),
    ]
